#!/usr/bin/env php
<?php

require_once dirname(__DIR__) . '/vendor/autoload.php';
require dirname(__DIR__) . '/config/doctrine.php';

use Doctrine\DBAL\DriverManager;
use Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper;
use Doctrine\Migrations\Configuration\Configuration;
use Doctrine\Migrations\Tools\Console\Command;
use Doctrine\Migrations\Tools\Console\Helper\ConfigurationHelper;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Helper\HelperSet;
use Symfony\Component\Console\Helper\QuestionHelper;
use Doctrine\ORM\Tools\Console\Helper\EntityManagerHelper;

$dbParams = [
    'dbname' => 'mvc',
    'user' => 'postgres',
    'password' => '',
    'host' => 'localhost',
    'driver' => 'pdo_pgsql',
];

$connection = DriverManager::getConnection($dbParams);

$configuration = new Configuration($connection);
$configuration->setName('My Project Migrations');
$configuration->setMigrationsNamespace('migrations');
$configuration->setMigrationsTableName('doctrine_migration_versions');
$configuration->setMigrationsColumnName('version');
$configuration->setMigrationsColumnLength(255);
$configuration->setMigrationsExecutedAtColumnName('executed_at');
$configuration->setMigrationsDirectory('../migrations');
$configuration->setAllOrNothing(true);
$configuration->setCheckDatabasePlatform(false);

$helperSet = new HelperSet();
$helperSet->set(new QuestionHelper(), 'question');
$helperSet->set(new ConnectionHelper($connection), 'db');
$helperSet->set(new ConfigurationHelper($connection, $configuration));
$helperSet->set(new EntityManagerHelper($entityManager));

$cli = new Application('Doctrine Migrations');
$cli->setCatchExceptions(true);
$cli->setHelperSet($helperSet);

$cli->addCommands(array(
    new Command\DumpSchemaCommand(),
    new Command\ExecuteCommand(),
    new Command\GenerateCommand(),
    new Command\LatestCommand(),
    new Command\MigrateCommand(),
    new Command\RollupCommand(),
    new Command\StatusCommand(),
    new Command\VersionCommand(),
    new Command\DiffCommand()
));

$cli->run();