<?php
/**
 * Created by PhpStorm.
 * User: Aziz Juraev
 * Date: 11.10.2020
 * Time: 18:01
 */

namespace core;


class NotfoundException extends \Exception
{

    public function __construct()
    {
        http_response_code(404);
        parent::__construct(); // TODO: Change the autogenerated stub
    }

}